android/gradle.properties, ios/LochaMeshChat.xcodeproj/project.pbxproj, src/i18n/en.json, src/i18n/es.json, src/i18n/index.js, src/index.js, src/views/LoadWallet/CreateAccount.js, src/views/LoadWallet/PinView.js, src/views/LoadWallet/RestoreWithPin.js, src/views/LoadWallet/index.js, src/views/config/EditName.js, src/views/config/EditPhoto.js, src/views/config/Language.js, src/views/config/ViewQR.js, src/views/config/index.js, src/views/home/index.js
cambios:
-  solventado el fallo de verificación cuando intentamos crear una cuenta.
- agregado el idioma español a la vistas de inicio y demas textos a los que faltaba agregar el i18n
-  solventado el bug de la imagen autogenerada de un usuario no aparece en la lista de chats.
- agregada mas sensibilidad a los botones de la vista de pin y  quitado el auto mayúscula  en los inputs de phrases
- cambiado el estilo de modal de seleccionar lenguaje
=> solved the last bugs reported in the app

CONTRIBUTING.md, package-lock.json
this PR is in order to fix index indentation
=> add indentation to index contributing file

src/i18n/en.json, src/i18n/es.json, src/store/aplication/aplicationAction.js, src/utils/socket.js, src/views/LoadWallet/AddName.js, src/views/LoadWallet/CreateAccount.js
=> added view to add the name when we are creating an account this 

android/app/src/main/java/DeviceInfo/DeviceInfoModule.java, android/app/src/main/java/DeviceInfo/DeviceInfoPackage.java, android/app/src/main/java/com/lochameshchat/MainApplication.java, ios/RNDeviceInfo.swift, src/components/Drawer.js, src/index.js
fix issue #33 
- added the app version in the menu
- added native module in java
- added function to obtain version information of the Swift device
=> added app version

src/components/Drawer.js, src/database/index.js, src/database/realmDatabase.js, src/database/schemas.js, src/store/aplication/aplicationAction.js, src/store/chats/chatAction.js, src/store/configuration/congurationAction.js, src/store/configuration/congurationReducer.js, src/store/constants.js, src/store/contacts/contactsActions.js, src/store/contacts/contactsReducer.js, src/utils/socket.js, src/utils/utils.js, src/views/contacts/AddContact.js, src/views/contacts/index.js, src/views/home/Chat.js
=> Request image

package.json, src/index.js, yarn.lock
an ESlint verification was added before committing this to prevent errors from breaking
=> adding pre-commit

src/index.js, src/views/deviceSettings/index.js, src/views/home/Chat.js
=> fixed the bug when sending images in the chat

README.md
=> 2020 05 15 update readme

App.js, __tests__/Views/deviceSettings/index.js, android/app/build.gradle, android/app/src/main/java/RNCoapClient/CoapClientModule.java, android/app/src/main/java/RNCoapClient/CoapClientPackage.java, android/app/src/main/java/com/lochameshchat/MainApplication.java, android/app/src/main/java/upd/RNUdpServerModule.java, android/app/src/main/java/upd/RNUdpServerPackage.java, src/index.js, src/store/deviceSettins/deviceSettingsAction.js, src/store/deviceSettins/deviceSettingsReducer.js, src/utils/socket.js, src/views/deviceSettings/index.js, src/views/deviceSettings/settingsPanel.js
a udp server was added to send messages, ready for review.
=> 2020 06 08 upd server

App.js, __tests__/Views/deviceSettings/index.js, android/app/build.gradle, android/app/src/main/java/RNCoapClient/CoapClientModule.java, android/app/src/main/java/RNCoapClient/CoapClientPackage.java, android/app/src/main/java/com/lochameshchat/MainApplication.java, src/index.js, src/store/deviceSettins/deviceSettingsAction.js, src/store/deviceSettins/deviceSettingsReducer.js, src/views/deviceSettings/index.js, src/views/deviceSettings/settingsPanel.js
=> 202 06  05 client coap implementation

src/WifiConnect.js, src/i18n/en.json, src/i18n/es.json
Just adds localization for the WifiConnect view, to reduce warnings in console logs :tada:
=> Add i18n entries for WifiConnect

android/app/src/main/java/io/locha/p2p/util/LibraryLoader.java, package.json, src/i18n/index.js, src/store/aplication/aplicationAction.js, src/store/deviceSettins/deviceSettingsAction.js, src/views/config/Language.js, yarn.lock
Fixes the warning of AsyncStorage that has been moved to `@react-native-community/async-storage`. Please review carefully as I don't have used JS too much :-)
=> Use AsyncStorage from @react-native-community/async-storage

src/components/Header.js, src/views/home/Chat.js
automatic connection in the chat view this improvement solves having to enter and exit the chat view every time the connection was lost.
=> automatic reconnection

src/store/aplication/aplicationAction.js, src/store/chats/chatAction.js, src/store/chats/chatReducers.js, src/views/LoadWallet/CreateAccount.js, src/views/LoadWallet/PinView.js, src/views/LoadWallet/RestoreWithPin.js, src/views/contacts/AddContact.js, src/views/home/Chat.js, src/views/home/ChatBody.js
- locked pin view so user can't add anything once request is made
- fixed edit contacts
- The status of the message is not being sent if you were in the chat
- error deleting a contact
=> bugs fixed

android/app/src/main/rust/Cargo.lock, android/app/src/main/rust/src/runtime.rs
=> Update locha-p2p crate to latest version

src/i18n/es.json, src/views/contacts/AddContact.js
Signed-off-by: Jean Pierre Dudey <me@jeandudey.tech>
=> Add i18n text for Peer ID in AddContact view

android/app/src/main/java/io/locha/p2p/service/EventsDispatcher.java, package.json, src/store/aplication/aplicationAction.js, src/store/deviceSettins/deviceSettingsAction.js, src/views/deviceSettings/index.js
the changes were made so that the device Settings view will no longer crash if a request fails
this fixes the issue #112
=> fixed bug in device view

.gitignore, App.js, __Mocks__/index.js, __tests__/Views/configuration/ AddNewAddressListen-test.js, __tests__/Views/configuration/AddManualAddress-test.js, __tests__/Views/configuration/AdministrativeComponent-test.js, __tests__/Views/configuration/index.js, __tests__/components/drawer-test.js, src/components/Drawer.js, src/database/index.js, src/utils/chatService.js, src/views/config/AddManualAddress.js, src/views/config/AddNewAddressListen.js, src/views/config/AdministrativeComponent.js, src/views/config/ViewQR.js
the last added components were tested
=> added unit tests to missing components

.github/workflows/build_apk.yml, android/gradle.properties.in, android/keystore.sh, package.json
Signed-off-by: Jean Pierre Dudey <me@jeandudey.tech>
=> Build release APK with GH Actions

android/app/src/main/rust/src/runtime.rs
Signed-off-by: Jean Pierre Dudey <me@jeandudey.tech>
=> Pass bootstrap nodes to RuntimeConfig

android/app/src/main/rust/Cargo.lock
=> updated locha-p2p

__Mocks__/index.js, __tests__/Actions/AplicationAction.js, __tests__/Views/chats/chatForm-test.js, android/app/src/main/rust/Cargo.lock, android/app/src/main/rust/Cargo.toml, src/components/Draggable.js, src/store/chats/chatAction.js, src/views/home/ChatForm.js, src/views/home/Messages.js
solved the problem of the audios
=> fixed the problem with the audios

package.json, yarn.lock
axios library was removed from package.json
=> removed axios

android/app/src/main/AndroidManifest.xml, android/app/src/main/java/DeviceInfo/Utils.java, android/app/src/main/java/io/locha/p2p/service/ChatService.java, android/app/src/main/java/io/locha/p2p/service/ChatServiceModule.java, android/app/src/main/java/io/locha/p2p/service/EventsDispatcher.java, src/utils/chatService.js
se agrego una validacion para cerrar el servicio cuando el dispositivo no tenga ninguna conexion, tambien el servicio se reinicia cuando hay un cambio en la red.
=> Reconection chat service

__tests__/Views/configuration/index.js, src/components/Drawer.js, src/views/config/index.js
=> fixed little bugs

package.json, yarn.lock
with this PR we solve the security problem of node-notifier
=> fixed security problems with the lib node_notifier

.github/workflows/nodejs.yml, __Mocks__/index.js, __tests__/Actions/AplicationAction.js, __tests__/ChatService-test.js, __tests__/Views/LoadWallet/PinView-test.js, __tests__/Views/configuration/ AddNewAddressListen-test.js, src/store/aplication/aplicationAction.js, src/store/chats/chatAction.js, src/utils/chatService.js, src/utils/utils.js, src/views/LoadWallet/PinView.js, src/views/home/Chat.js, src/views/home/ChatBody.js, src/views/home/imagesView/index.js
Problems solved
- it's was removed randoms numbers in the pin
- error with images was fixed
- error with message status in the contact was solved
Problems not found
- start chat service in Samsung s10 with phone signal
- delete messages in Samsung s10
=> Fix small bugs v2
